[package]
name = "flights"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
color_space = "0.5.4"
rust-tuyapi = "0.9.1"
serde = "1.0.228"
serde_json = "1.0.149"
